spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.open-in-view: false
server.port: 9333
#配置方言
spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
spring.datasource.platform: MySQL
# 配置默认数据源，并使用 阿里连接池
spring.datasource.type: com.alibaba.druid.pool.DruidDataSource
#spring.datasource.url :  jdbc:mysql://sh-cdb-mbj6mdpc.sql.tencentcdb.com:61732/db_warn?useUnicode: true&characterEncoding: UTF-8&serverTimezone: Asia/Shanghai
#spring.datasource.username :  myy
#spring.datasource.password :  myyun@r@myy
spring.datasource.url: jdbc:mysql://sh-cdb-mbj6mdpc.sql.tencentcdb.com:61732/db_river?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
spring.datasource.username: ssr
spring.datasource.password: myyun@r@srr
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.max-active: 20
spring.datasource.max-idle: 8
spring.datasource.min-idle: 8
spring.datasource.initial-size: 10
## Redis 配置
## Redis数据库索引（默认为0）
#spring.redis.database: 0
## Redis服务器地址
spring.redis.host: 127.0.0.1
## Redis服务器连接端口
spring.redis.port: 6379
## Redis服务器连接密码（默认为空）
spring.redis.password: 
## 连接池最大连接数（使用负值表示没有限制）
#spring.redis.jedis.pool.max-active: 8
## 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.jedis.pool.max-wait: -1
## 连接池中的最大空闲连接
#spring.redis.jedis.pool.max-idle: 8
## 连接池中的最小空闲连接
#spring.redis.jedis.pool.min-idle: 0
## 连接超时时间（毫秒）
#spring.redis.timeout: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://moyuan:moyuan123@localhost:8010/eureka/

spring:
  application:
    name: myy-security