server:
  port: 8050
#  servlet:
#    context-path: /Path
spring:
  application:
    name: myy-baseserver
  datasource:
    url: jdbc:mysql://sh-cdb-mbj6mdpc.sql.tencentcdb.com:61732/db_river?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ssr
    password: myyun@r@srr
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 10
      minIdle: 8
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      filters: stat,wall,log4j
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-idle: 500  # 最大空闲连接数
        min-idle: 50   # 最小空闲连接数
        max-wait:  -1s # 等待可用连接的最大时间，负数为不限制
        max-active: -1 # 最大活跃连接数，负数为不限制
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

eureka:
  client:
    serviceUrl:
      defaultZone: http://moyuan:moyuan123@localhost:8010/eureka/

feign:
  hystrix:
    enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          #配置hystrix的超时时间
          thread:
            timeoutInMilliseconds: 20000
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
#logging:
#  config: classpath:log4j2.xml
